# Cleaning Data

### Loading libraries

The libraries used are pandas for data manipulation, numpy for array computations (especially nans).

In [1]:
import pandas as pd
import numpy as np
from numpy import nan
np.set_printoptions(suppress=True) # This suppress scientific notation for numpy printouts

### Loading the dataset

we loaded the csv file into a pandas DataFrame named 'movies'

In [2]:
movies = pd.read_csv('Team6_movies_dataset.csv')

In [3]:
movies.shape

(200, 32)

The dataframe contains 200 rows and 32 columns.

### Column cleaning

In this section we will clean the column names so they look homogeneous, without extra (invisible) characters.

First of all, we print a list of column names.

In [4]:
movies.columns #knowing that we had an extra average column we then...
movies.drop('Average', axis=1, inplace=True) #Decided to remove the column with this code
movies.columns # We print again the columns and see that the average column was removed correctly

Index(['Movie', 'Year', 'Runtime', 'Genre', 'Budget', 'Revenue', 'IMDb',
       'Metacritic', 'Rotten Tomatoes', 'Filmaffinity', 'Personal', 'P1', 'P2',
       'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13',
       'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20'],
      dtype='object')

We then decided to copy the current columns in a list so we can reorder the placement of each

In [5]:
movies = movies[['Movie', 'Year', 'Runtime', 'Genre', 'Budget', 'Revenue', 'IMDb',
       'Metacritic', 'Rotten Tomatoes', 'Filmaffinity', 'Personal',
       'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11',
       'P12', 'P13', 'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20']]
#Here is the copy of the columns

column_names = ['Title', 'Year', 'Runtime', 'Genre', 'Budget', 'Revenue', 'Personal', 'IMDb', 'Rotten_Tomatoes', 'Metacritic', 'Filmaffinity', 'P1', 'P2',
       'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9', 'P10', 'P11', 'P12', 'P13',
       'P14', 'P15', 'P16', 'P17', 'P18', 'P19', 'P20']
#Here is the "correct" order

movies.columns = column_names # Here we applied the new column names to the DataFrame.

Finally, we will set the `Title` column as the indexing column of our dataframe.

In [6]:
movies.set_index('Title', inplace=True) #this command sets the 'Title' column as the index of the DataFrame.

### Data cleaning

We will follow the guidelines stated below for cleaning the data for each column:
- `Year`: This column will be left unchanged for the time being. Data type can be `str` or `int`. It it isn't, we will recast it later.
- `Runtime`: Data type should be `int`. Remove any indication to a unit of measurement.
- `Genre`: Data type should be `str`. We will capitalize the data, and if there is more than one genre, we will keep the first one and remove the rest.
- `Budget`: Data type can be `int` or `float`. To that end, we will remove dollar signs as well as the thousands separator. We will scale the data so the unit of measurment is millions of dollars.
- `Revenue`: Same treatment as that of `Budget`.
- Rating columns: Data type can be `int` or `float`. Change scale to [0,100].

Let's explore the type of each of the columns. In the table below we can also see if there is missing data.

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, (500) Days of Summer to The Social Network
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             200 non-null    int64
 1   Runtime          200 non-null    int64
 2   Genre            200 non-null    object
 3   Budget           199 non-null    float64
 4   Revenue          199 non-null    object
 5   Personal         200 non-null    int64
 6   IMDb             199 non-null    float64
 7   Rotten_Tomatoes  200 non-null    int64
 8   Metacritic       200 non-null    int64
 9   Filmaffinity     200 non-null    int64
 10  P1               181 non-null    float64
 11  P2               174 non-null    float64
 12  P3               179 non-null    float64
 13  P4               181 non-null    float64
 14  P5               187 non-null    float64
 15  P6               188 non-null    float64
 16  P7               179 non-null    float64
 17  P8               176 non-null    float64
 18  P9               176 non-null    float64
 19  P10              181 non-null    float64
 20  P11              186 non-null    float64
 21  P12              184 non-null    float64
 22  P13              174 non-null    float64
 23  P14              181 non-null    float64
 24  P15              177 non-null    float64
 25  P16              180 non-null    float64
 26  P17              185 non-null    float64
 27  P18              179 non-null    float64
 28  P19              179 non-null    float64
 29  P20              186 non-null    float64
dtypes: float64(22), int64(6), object(2)
memory usage: 48.4+ KB

We can appreciate that Revenue has a type object and it should be an int or a float the rest of the columns have a correct type. And also the non-null count per column looks right.

#### `Runtime`

In [8]:
np.sort(movies['Runtime'].unique()) #this prints the Runtime column sorting from lowest to highest and only showing unique values

array([ 81,  83,  86,  87,  88,  89,  90,  91,  92,  94,  95,  97,  98,
        99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 146, 147, 148, 149, 150, 151, 152, 153, 154,
       155, 156, 158, 162, 163, 164, 165, 166, 169, 170, 175, 176, 180,
       181, 189, 192, 194, 195])

Here we can see that the runtime values look fine.

#### `Budget` and `Revenue`

In [9]:
np.sort(movies['Budget'].unique())  #this prints the Budget column sorting from lowest to highest and only showing unique values

array([  1. ,   1.2,   1.3,   1.5,   2. ,   2.6,   3. ,   3.3,   3.5,
         4. ,   4.5,   5. ,   6. ,   6.4,   6.5,   7. ,   7.5,   8. ,
         8.5,   9. ,  10. ,  11. ,  13. ,  14. ,  15. ,  16. ,  18. ,
        18.5,  19. ,  19.5,  20. ,  22. ,  23. ,  25. ,  28. ,  30. ,
        31. ,  33. ,  34. ,  36. ,  40. ,  44.5,  45. ,  46. ,  47. ,
        50. ,  52. ,  55. ,  58. ,  60. ,  61. ,  63. ,  65. ,  68. ,
        70. ,  75. ,  76. ,  80. ,  90. ,  92. ,  96. ,  97. , 100. ,
       103. , 108. , 110. , 113. , 115. , 118. , 120. , 125. , 135. ,
       145. , 150. , 160. , 165. , 170. , 175. , 178. , 185. , 190. ,
       200. , 237. , 250. , 291. , 300. , 400. , 426. , 460. ,   nan])

Also here we can see that the budget collumn looks fine. But there is a nan value which we already knew it had because when we looked at the columns info

In [10]:
movies['Revenue'].unique()

array(['61', '54', '85.7', '436.2', '32.8', '350.9', '174.2', '34', '57',
       '47', '2,920', '2,320', '2800', '2052', '227', '381.1', '332',
       '244', '135.9', '1447', '376', '1,009', '1.081', '435.3', '103.2',
       '1,348.30', '329', '41.8', '277', '4.1', '55', '235', '2,900',
       '786.4', '1,300', '18.2', '100', '410', '715', '6.4', '72', '600',
       '46.2', '295.5', '678', '250', '1,140', '503.5', '168', '226',
       '47.1', '723.2', '259.5', '48.8', '800', '321', '858.8', '731.6',
       '87.8', '171.5', '327.7', '447.3', '90.4', '1,670.00', '1,109.70',
       '130', '180', '44.6', '313', '15.3', '70', '472', '619', '380.4',
       '457.7', '546.4', '398.5', '571.1', '791', '694.7', '682.7', '598',
       '65.3', '50.3', '171.6', '172.3', '181', nan, '17', '976', '411.1',
       '258', '200', '623', '104', '65.7', '173', '327', '492', '294',
       '365', '690', '394', '1,910', '775', '649', '902.9', '396', '28.5',
       '76.2', '550', '216.7', '78.4', '10.3', '772', '133.4', '51.5',
       '493', '291', '174', '12', '49.2', '233.6', '1074.3', '432.4',
       '18.1', '968.5', '630.2', '460', '79', '33', '109.7', '532.9',
       '195.2', '45', '82', '123.7', '20', '264', '389', '2,201.60',
       '362', '511.4', '1,067', '1,073', '409.9', '50', '184', '183',
       '356', '92', '232', '133', '46', '8.6', '910', '43', '49', '352',
       '29', '30', '814', '220', '7.5', '81', '86', '37', '60', '11',
       '1280', '120', '286', '187', '185', '631', '476', '521', '1005',
       '609', '275', '119', '40', '217', '157', '83', '122', '7.4', '225',
       '322', '85', '378', '273'], dtype=object)

Here in Revenue column we can notice that there are numbers surpasing 3 digits that contain a comma like '1,910', so we need to remove commas. And most importat we knew that Revenue was an object type, so we'll change it to numeric.

In [11]:
movies['Revenue']=movies['Revenue'].str.replace(',', '') # This replaces the commas with a white space
movies['Revenue']=pd.to_numeric(movies['Revenue'], errors='coerce') # conversion to numeric, coercing any remaining errors to NaN.
np.sort(movies['Revenue'].unique())

array([   1.081,    4.1  ,    6.4  ,    7.4  ,    7.5  ,    8.6  ,
         10.3  ,   11.   ,   12.   ,   15.3  ,   17.   ,   18.1  ,
         18.2  ,   20.   ,   28.5  ,   29.   ,   30.   ,   32.8  ,
         33.   ,   34.   ,   37.   ,   40.   ,   41.8  ,   43.   ,
         44.6  ,   45.   ,   46.   ,   46.2  ,   47.   ,   47.1  ,
         48.8  ,   49.   ,   49.2  ,   50.   ,   50.3  ,   51.5  ,
         54.   ,   55.   ,   57.   ,   60.   ,   61.   ,   65.3  ,
         65.7  ,   70.   ,   72.   ,   76.2  ,   78.4  ,   79.   ,
         81.   ,   82.   ,   83.   ,   85.   ,   85.7  ,   86.   ,
         87.8  ,   90.4  ,   92.   ,  100.   ,  103.2  ,  104.   ,
        109.7  ,  119.   ,  120.   ,  122.   ,  123.7  ,  130.   ,
        133.   ,  133.4  ,  135.9  ,  157.   ,  168.   ,  171.5  ,
        171.6  ,  172.3  ,  173.   ,  174.   ,  174.2  ,  180.   ,
        181.   ,  183.   ,  184.   ,  185.   ,  187.   ,  195.2  ,
        200.   ,  216.7  ,  217.   ,  220.   ,  225.   ,  226.   ,
        227.   ,  232.   ,  233.6  ,  235.   ,  244.   ,  250.   ,
        258.   ,  259.5  ,  264.   ,  273.   ,  275.   ,  277.   ,
        286.   ,  291.   ,  294.   ,  295.5  ,  313.   ,  321.   ,
        322.   ,  327.   ,  327.7  ,  329.   ,  332.   ,  350.9  ,
        352.   ,  356.   ,  362.   ,  365.   ,  376.   ,  378.   ,
        380.4  ,  381.1  ,  389.   ,  394.   ,  396.   ,  398.5  ,
        409.9  ,  410.   ,  411.1  ,  432.4  ,  435.3  ,  436.2  ,
        447.3  ,  457.7  ,  460.   ,  472.   ,  476.   ,  492.   ,
        493.   ,  503.5  ,  511.4  ,  521.   ,  532.9  ,  546.4  ,
        550.   ,  571.1  ,  598.   ,  600.   ,  609.   ,  619.   ,
        623.   ,  630.2  ,  631.   ,  649.   ,  678.   ,  682.7  ,
        690.   ,  694.7  ,  715.   ,  723.2  ,  731.6  ,  772.   ,
        775.   ,  786.4  ,  791.   ,  800.   ,  814.   ,  858.8  ,
        902.9  ,  910.   ,  968.5  ,  976.   , 1005.   , 1009.   ,
       1067.   , 1073.   , 1074.3  , 1109.7  , 1140.   , 1280.   ,
       1300.   , 1348.3  , 1447.   , 1670.   , 1910.   , 2052.   ,
       2201.6  , 2320.   , 2800.   , 2900.   , 2920.   ,      nan])

We can see that now the column looks fine, but there is a movie that had a very little revenue, we need to check if this is correct by searching for the movie by the revenue:

In [12]:
movies[(movies['Revenue'] >= 1.0) & (movies['Revenue'] <= 1.9)]

,Year,Runtime,Genre,Budget,Revenue,Personal,IMDb,Rotten_Tomatoes,Metacritic,Filmaffinity,...,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20
Title,,,,,,,,,,,,,,,,,,,,,
Batman Dark Knight Rises,2012,165,Action,250.0,1.081,84,78.0,87,75,92,...,6.0,76.0,NaN,79.0,55.0,88.0,97.0,70.0,88.0,47.0

We can see that the movie Batman Dark Knight Rises has a revenue of $1,081,000 which is not right... and according to **Box Office Mojo**, the revenue for this movie is \$1,081,000,000 dollars so we will replace the given range with 1081.

In [13]:
movies.at['Batman Dark Knight Rises','Revenue'] = 1081. # replaces the old revenue to 1081. for the movie

Now, we clean the rest of the column

In [14]:
# We convert the column back to a string type to remove extra spaces if there are
movies['Revenue'] = movies['Revenue'].astype(str)
movies['Revenue'] = movies['Revenue'].str.replace(' ', '', regex=False) # Remove spaces too, just in case
# And finally convert it back to numeric and print to check if everything is right
movies['Revenue']=pd.to_numeric(movies['Revenue'], errors='coerce')
np.sort(movies['Revenue'].unique())

array([   4.1,    6.4,    7.4,    7.5,    8.6,   10.3,   11. ,   12. ,
         15.3,   17. ,   18.1,   18.2,   20. ,   28.5,   29. ,   30. ,
         32.8,   33. ,   34. ,   37. ,   40. ,   41.8,   43. ,   44.6,
         45. ,   46. ,   46.2,   47. ,   47.1,   48.8,   49. ,   49.2,
         50. ,   50.3,   51.5,   54. ,   55. ,   57. ,   60. ,   61. ,
         65.3,   65.7,   70. ,   72. ,   76.2,   78.4,   79. ,   81. ,
         82. ,   83. ,   85. ,   85.7,   86. ,   87.8,   90.4,   92. ,
        100. ,  103.2,  104. ,  109.7,  119. ,  120. ,  122. ,  123.7,
        130. ,  133. ,  133.4,  135.9,  157. ,  168. ,  171.5,  171.6,
        172.3,  173. ,  174. ,  174.2,  180. ,  181. ,  183. ,  184. ,
        185. ,  187. ,  195.2,  200. ,  216.7,  217. ,  220. ,  225. ,
        226. ,  227. ,  232. ,  233.6,  235. ,  244. ,  250. ,  258. ,
        259.5,  264. ,  273. ,  275. ,  277. ,  286. ,  291. ,  294. ,
        295.5,  313. ,  321. ,  322. ,  327. ,  327.7,  329. ,  332. ,
        350.9,  352. ,  356. ,  362. ,  365. ,  376. ,  378. ,  380.4,
        381.1,  389. ,  394. ,  396. ,  398.5,  409.9,  410. ,  411.1,
        432.4,  435.3,  436.2,  447.3,  457.7,  460. ,  472. ,  476. ,
        492. ,  493. ,  503.5,  511.4,  521. ,  532.9,  546.4,  550. ,
        571.1,  598. ,  600. ,  609. ,  619. ,  623. ,  630.2,  631. ,
        649. ,  678. ,  682.7,  690. ,  694.7,  715. ,  723.2,  731.6,
        772. ,  775. ,  786.4,  791. ,  800. ,  814. ,  858.8,  902.9,
        910. ,  968.5,  976. , 1005. , 1009. , 1067. , 1073. , 1074.3,
       1081. , 1109.7, 1140. , 1280. , 1300. , 1348.3, 1447. , 1670. ,
       1910. , 2052. , 2201.6, 2320. , 2800. , 2900. , 2920. ,    nan])

#### Ratings

In [15]:
rating_columns=movies.columns[5:] #Basicly remove the first 5 columns for better handeling of the rating columns
for col in rating_columns:
    print(f"{col} = {np.sort(movies[col].unique())}")

Personal = [52 54 61 62 63 64 65 66 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89 90 91 92 94]
IMDb = [ 33.  46.  48.  49.  51.  54.  55.  56.  57.  58.  59.  60.  61.  62.
  63.  64.  65.  66.  67.  68.  69.  70.  71.  72.  73.  74.  75.  76.
  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.
  91.  92.  93.  94.  95.  96.  98.  99. 100.  nan]
Rotten_Tomatoes = [ 32  45  50  51  54  55  57  60  62  63  66  68  69  71  72  73  76  77
  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95
  96  97  98  99 100]
Metacritic = [43 48 51 55 56 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76
 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
Filmaffinity = [  5  10  15  23  24  25  30  32  36  40  45  50  56  59  60  61  65  66
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]
P1 = [  0.   3.   4.   5.   6.   8.   9.  10.  13.  14.  16.  20.  23.  24.
  27.  28.  30.  31.  34.  36.  37.  39.  40.  41.  43.  44.  45.  46.
  47.  48.  50.  51.  53.  54.  55.  56.  57.  58.  60.  61.  62.  63.
  64.  66.  67.  69.  70.  71.  72.  73.  75.  76.  77.  78.  79.  80.
  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.
  95.  96.  97.  98.  99. 100.  nan]
P2 = [  0.   2.   4.   6.   9.  12.  14.  16.  17.  19.  20.  21.  23.  24.
  25.  26.  27.  28.  29.  30.  31.  32.  35.  37.  44.  45.  47.  49.
  50.  51.  52.  53.  58.  61.  62.  63.  64.  65.  67.  68.  69.  70.
  71.  72.  73.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.
  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99.
 100.  nan]
P3 = [  0.   3.   4.   5.   6.   7.   8.  10.  11.  15.  16.  17.  18.  19.
  20.  21.  22.  23.  27.  28.  29.  30.  31.  32.  33.  35.  36.  41.
  42.  44.  45.  49.  50.  53.  54.  57.  58.  59.  60.  61.  62.  63.
  64.  66.  67.  68.  69.  70.  71.  72.  75.  76.  77.  78.  79.  80.
  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.
  95.  96.  97.  98.  99. 100.  nan]
P4 = [  1.   2.   3.   4.   5.   8.  10.  11.  12.  14.  15.  18.  19.  23.
  25.  27.  29.  30.  31.  32.  34.  36.  38.  40.  42.  43.  45.  47.
  48.  49.  50.  51.  52.  53.  54.  55.  56.  59.  62.  65.  66.  68.
  69.  71.  72.  73.  74.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.  nan]
P5 = [  2.   3.   4.   6.   7.   8.   9.  12.  13.  14.  17.  20.  21.  22.
  23.  24.  27.  29.  30.  32.  33.  34.  35.  36.  37.  38.  39.  42.
  44.  45.  48.  49.  51.  52.  53.  54.  55.  58.  59.  61.  62.  64.
  65.  68.  70.  72.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.
  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99.
 100.  nan]
P6 = [  1.   3.   4.   6.   7.   9.  12.  14.  17.  18.  20.  21.  22.  23.
  24.  25.  26.  29.  33.  34.  38.  39.  41.  42.  43.  44.  45.  46.
  48.  49.  51.  52.  53.  54.  55.  56.  58.  59.  60.  61.  63.  65.
  66.  68.  69.  70.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.  nan]
P7 = [  1.   2.   3.   4.   6.   7.   8.  13.  16.  18.  19.  23.  24.  26.
  27.  28.  35.  36.  37.  38.  39.  40.  41.  42.  45.  46.  47.  48.
  49.  53.  54.  55.  56.  59.  60.  61.  62.  63.  64.  65.  68.  69.
  70.  71.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.
  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99.
 100.  nan]
P8 = [  2.   4.   5.   6.   8.   9.  10.  11.  12.  14.  15.  17.  18.  19.
  20.  21.  22.  23.  29.  30.  31.  32.  33.  40.  41.  45.  47.  48.
  50.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.  64.  65.  66.
  67.  69.  70.  72.  74.  75.  76.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.  nan]
P9 = [  1.   2.   4.   5.   7.   9.  12.  14.  16.  19.  20.  24.  25.  26.
  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  38.  39.  41.  43.
  44.  45.  46.  47.  48.  49.  51.  53.  54.  55.  56.  59.  60.  61.
  64.  65.  67.  68.  69.  70.  72.  73.  74.  75.  76.  77.  78.  79.
  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.
  94.  95.  96.  97.  98.  99. 100.  nan]
P10 = [  0.   2.   3.   4.   5.   6.   7.   9.  13.  14.  15.  16.  17.  18.
  19.  20.  22.  24.  25.  27.  28.  29.  30.  31.  32.  34.  35.  36.
  37.  43.  44.  45.  46.  47.  50.  52.  53.  54.  55.  57.  59.  61.
  64.  65.  66.  67.  69.  71.  73.  74.  76.  77.  78.  79.  80.  81.
  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.
  96.  97.  98.  99. 100.  nan]
P11 = [  1.   4.   5.   6.   8.  10.  11.  12.  13.  15.  16.  17.  19.  20.
  22.  23.  24.  25.  27.  31.  32.  34.  35.  37.  39.  41.  42.  45.
  47.  50.  51.  53.  55.  56.  57.  58.  59.  60.  62.  63.  64.  65.
  66.  68.  69.  70.  72.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.  nan]
P12 = [  0.   1.   5.   7.   8.   9.  11.  12.  13.  15.  16.  17.  19.  20.
  22.  27.  28.  29.  30.  33.  35.  37.  39.  40.  41.  43.  44.  46.
  48.  49.  51.  53.  54.  55.  56.  57.  58.  59.  62.  63.  67.  68.
  71.  72.  73.  74.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.
  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99.
 100.  nan]
P13 = [  1.   2.   9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.
  21.  22.  23.  24.  25.  26.  27.  29.  30.  31.  32.  35.  36.  37.
  38.  40.  41.  43.  44.  45.  46.  48.  49.  50.  55.  57.  59.  61.
  62.  63.  64.  65.  67.  70.  71.  74.  76.  77.  78.  79.  80.  81.
  82.  83.  84.  85.  86.  88.  89.  90.  91.  92.  93.  94.  95.  96.
  97.  98.  99. 100.  nan]
P14 = [  1.   2.   3.   4.   7.  11.  13.  14.  15.  16.  17.  18.  20.  21.
  22.  23.  24.  26.  27.  28.  29.  30.  31.  34.  37.  39.  40.  41.
  45.  48.  50.  51.  52.  54.  55.  57.  60.  61.  62.  63.  64.  66.
  69.  72.  73.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.
  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99. 100.
  nan]
P15 = [  2.   3.   4.   5.   7.   9.  12.  16.  17.  19.  20.  22.  23.  24.
  28.  29.  30.  34.  35.  36.  37.  38.  42.  44.  46.  47.  49.  50.
  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.  63.  66.  67.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  93.  94.  95.  96.  97.  98.  99.
 100.  nan]
P16 = [  1.   2.   3.   4.   8.   9.  10.  12.  13.  15.  16.  17.  18.  19.
  22.  23.  25.  26.  27.  30.  31.  33.  36.  38.  42.  43.  44.  46.
  48.  49.  50.  53.  55.  56.  57.  59.  60.  63.  64.  65.  67.  70.
  72.  73.  75.  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.  87.
  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99. 100.  nan]
P17 = [  0.   1.   4.   6.   7.   9.  10.  11.  12.  14.  15.  16.  17.  20.
  21.  22.  23.  24.  25.  26.  27.  28.  30.  33.  34.  35.  36.  38.
  41.  43.  46.  47.  50.  52.  53.  54.  55.  57.  58.  60.  61.  65.
  66.  67.  68.  69.  70.  72.  73.  75.  76.  77.  78.  79.  80.  81.
  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  94.  95.  96.
  97.  98.  99. 100.  nan]
P18 = [  0.   3.   4.   5.   7.   8.   9.  10.  12.  13.  14.  16.  17.  18.
  19.  20.  21.  23.  25.  26.  29.  31.  32.  38.  40.  41.  42.  43.
  44.  46.  47.  49.  50.  51.  54.  56.  57.  59.  60.  61.  67.  68.
  70.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.
  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99.
 100.  nan]
P19 = [  3.   4.   5.   6.   8.   9.  10.  11.  13.  15.  17.  18.  21.  22.
  23.  27.  28.  31.  33.  34.  36.  37.  40.  42.  43.  45.  47.  48.
  50.  53.  54.  55.  57.  58.  59.  60.  63.  64.  65.  70.  71.  73.
  74.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.  87.  88.
  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.  99. 100.  nan]
P20 = [  0.   1.   2.   3.   5.   8.   9.  10.  14.  15.  18.  19.  20.  22.
  25.  26.  27.  28.  29.  32.  33.  35.  37.  40.  42.  43.  44.  45.
  46.  47.  48.  49.  51.  52.  54.  56.  57.  58.  59.  60.  61.  62.
  65.  69.  70.  72.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.
  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.
  98.  99. 100.  nan]

We suspect that ratings smaller than $5$ are in a scale from $0$ to $5$, and ratings between $5$ and $10$ are in a scale from $0$ to $10$ so we multiply them by the proper factor to bring them up to a scale from $0$ to $100$.

In [16]:
# Prints all the movies that have a rating of 5 or below
for col in rating_columns:
    print(movies[(movies[col]>0)&(movies[col]<=5)][col].sort_values())

Series([], Name: Personal, dtype: int64)
Series([], Name: IMDb, dtype: float64)
Series([], Name: Rotten_Tomatoes, dtype: int64)
Series([], Name: Metacritic, dtype: int64)
Title
Forrest Gump    5
Name: Filmaffinity, dtype: int64
Title
The Godfather    3.0
Drive            3.0
Ratatouille      4.0
Prisoners        4.0
Lincoln          5.0
Name: P1, dtype: float64
Title
Deadpool 2           2.0
Challengers          2.0
Black Swan           4.0
Avengers: Endgame    4.0
Ex Machina           4.0
Name: P2, dtype: float64
Title
The Thing        3.0
The Lion King    3.0
Nop              4.0
Casablanca       5.0
Argo             5.0
Name: P3, dtype: float64
Title
Apocalypse Now      1.0
Am?lie              2.0
John Wick 4         2.0
F1                  3.0
Get Out             4.0
Nosferatu (1922)    5.0
Name: P4, dtype: float64
Title
Pan?s Labyrinth             2.0
The Silence of the Lambs    3.0
Spirited Away               4.0
Anora                       4.0
The Big Lebowski            4.0
Name: P5, dtype: float64
Title
Adaptation (Ladron de Orquideas)    1.0
The Matrix                          3.0
Sicario                             3.0
La Haine                            4.0
Name: P6, dtype: float64
Title
American Psycho            1.0
Pulp fiction               1.0
Ted 2                      1.0
Knives Out                 2.0
The Wolf of Wall Street    3.0
Casablanca                 4.0
Name: P7, dtype: float64
Title
Argo          2.0
Demolition    4.0
Logan         5.0
Frances Ha    5.0
Name: P8, dtype: float64
Title
Blue Velvet              1.0
Mission: Impossible 2    2.0
Shutter Island           4.0
Se7en                    4.0
Aliens (1986)            5.0
Name: P9, dtype: float64
Title
Kill Bill: Vol. 1                               2.0
Ghostbusters                                    3.0
Star Wars: Episode III - Revenge of the Sith    4.0
The Godfather                                   5.0
Joker: Folie ? Deux (2024)                      5.0
Name: P10, dtype: float64
Title
Lady Bird                          1.0
La Haine                           4.0
The Fantastic Four: First Steps    4.0
Coco                               5.0
Name: P11, dtype: float64
Title
Spider-Man: Into the Spider-Verse    1.0
Spider-Man: No Way Home              5.0
Name: P12, dtype: float64
Title
Terminator 1    1.0
John Wick       2.0
Name: P13, dtype: float64
Title
Big Hero 6            1.0
The Breakfast Club    2.0
Pan?s Labyrinth       2.0
The Substance         2.0
Boyhood               3.0
Birdman               3.0
Oppenheimer           4.0
Bohemian Rhapsody     4.0
Name: P14, dtype: float64
Title
Ex Machina            2.0
Toy Story 4           3.0
Casablanca            4.0
Dune                  4.0
Ghost in the Shell    4.0
Good Will Hunting     5.0
Shutter Island        5.0
Name: P15, dtype: float64
Title
Call Me by Your Name    1.0
Edward Scissorhands     2.0
Challengers             3.0
Ballerina               4.0
Nosferatu (1922)        4.0
Black Panther           4.0
Lincoln                 4.0
Name: P16, dtype: float64
Title
Batman Dark Knight                 1.0
The Perks of Being a Wallflower    1.0
The Batman                         4.0
Children of Men                    4.0
Name: P17, dtype: float64
Title
Star Wars: Episode I - The Phantom Menace     3.0
Anora                                         4.0
Kill Bill: Vol. 1                             4.0
Gone Girl                                     5.0
Name: P18, dtype: float64
Title
The Babadook          3.0
Nop                   3.0
Jojo Rabbit           4.0
Back to the Future    5.0
Name: P19, dtype: float64
Title
The Breakfast Club    1.0
Nosferatu (1922)      2.0
Alien: Romulus        3.0
Fantastic Mr. Fox     5.0
Mad Max: Fury Road    5.0
Name: P20, dtype: float64

In [17]:
# Prints all the movies that have a rating of 10 or below
for col in rating_columns:
    print(movies[(movies[col]>0)&(movies[col]<=10)][col].sort_values())

Series([], Name: Personal, dtype: int64)
Series([], Name: IMDb, dtype: float64)
Series([], Name: Rotten_Tomatoes, dtype: int64)
Series([], Name: Metacritic, dtype: int64)
Title
Forrest Gump     5
Barbie          10
Name: Filmaffinity, dtype: int64
Title
Drive                  3.0
The Godfather          3.0
Ratatouille            4.0
Prisoners              4.0
Lincoln                5.0
Terminator 1           6.0
Dead Poets Society     8.0
The Menu               9.0
The Thing             10.0
Se7en                 10.0
Name: P1, dtype: float64
Title
Deadpool 2           2.0
Challengers          2.0
Black Swan           4.0
Avengers: Endgame    4.0
Ex Machina           4.0
Pulp fiction         6.0
Life of Pi           9.0
Name: P2, dtype: float64
Title
The Lion King                                  3.0
The Thing                                      3.0
Nop                                            4.0
Casablanca                                     5.0
Argo                                           5.0
Am?lie                                         6.0
Star Wars: Episode I - The Phantom Menace      7.0
Batman Dark Knight                             7.0
Blade Runner 2049                              8.0
Parasite                                      10.0
Name: P3, dtype: float64
Title
Apocalypse Now       1.0
Am?lie               2.0
John Wick 4          2.0
F1                   3.0
Get Out              4.0
Nosferatu (1922)     5.0
Black Swan           8.0
Jurassic Park       10.0
Name: P4, dtype: float64
Title
Pan?s Labyrinth                                  2.0
The Silence of the Lambs                         3.0
Anora                                            4.0
The Big Lebowski                                 4.0
Spirited Away                                    4.0
Scarface                                         6.0
Demolition                                       7.0
Adaptation (Ladron de Orquideas)                 8.0
Oppenheimer                                      8.0
Spider-Man: No Way Home                          9.0
John Wick: Chapter 2                             9.0
Mission: Impossible - Dead Reckoning Part One    9.0
City of God (Cidade de Deus)                     9.0
Name: P5, dtype: float64
Title
Adaptation (Ladron de Orquideas)    1.0
Sicario                             3.0
The Matrix                          3.0
La Haine                            4.0
Avatar                              6.0
The Lion King                       7.0
Scarface                            7.0
Knives Out                          9.0
Name: P6, dtype: float64
Title
American Psycho            1.0
Pulp fiction               1.0
Ted 2                      1.0
Knives Out                 2.0
The Wolf of Wall Street    3.0
Casablanca                 4.0
The Karate Kid             6.0
Ex Machina                 7.0
The Green Mile             7.0
American Beauty            8.0
Argo                       8.0
Name: P7, dtype: float64
Title
Argo                                             2.0
Demolition                                       4.0
Logan                                            5.0
Frances Ha                                       5.0
The Babadook                                     6.0
Star Wars: Episode III - Revenge of the Sith     6.0
Boyhood                                          8.0
Call Me by Your Name                             8.0
Mission: Impossible 3                            9.0
Am?lie                                          10.0
Parasite                                        10.0
Name: P8, dtype: float64
Title
Blue Velvet              1.0
Mission: Impossible 2    2.0
Se7en                    4.0
Shutter Island           4.0
Aliens (1986)            5.0
Killer Clowns            7.0
Pacific Rim              7.0
A Star is Born           9.0
Name: P9, dtype: float64
Title
Kill Bill: Vol. 1                               2.0
Ghostbusters                                    3.0
Star Wars: Episode III - Revenge of the Sith    4.0
The Godfather                                   5.0
Joker: Folie ? Deux (2024)                      5.0
Drive                                           6.0
Dune: Part Two                                  7.0
No Country for Old Men                          9.0
Scarface                                        9.0
Name: P10, dtype: float64
Title
Lady Bird                                      1.0
La Haine                                       4.0
The Fantastic Four: First Steps                4.0
Coco                                           5.0
Batman Dark Knight Rises                       6.0
Batman Dark Knight                             8.0
Star Wars: Episode I - The Phantom Menace     10.0
Name: P11, dtype: float64
Title
Spider-Man: Into the Spider-Verse     1.0
Spider-Man: No Way Home               5.0
Taxi Driver                           7.0
John Wick                             8.0
Star Wars: Episode IV - A New Hope    8.0
Jurassic World                        9.0
Mission: Impossible - Rogue Nation    9.0
The Martian                           9.0
Name: P12, dtype: float64
Title
Terminator 1      1.0
John Wick         2.0
Big Hero 6        9.0
28 days later     9.0
Spirited Away    10.0
Name: P13, dtype: float64
Title
Big Hero 6                    1.0
The Breakfast Club            2.0
The Substance                 2.0
Pan?s Labyrinth               2.0
Boyhood                       3.0
Birdman                       3.0
Oppenheimer                   4.0
Bohemian Rhapsody             4.0
Batman Begins                 7.0
Back to the Future Part II    7.0
Name: P14, dtype: float64
Title
Ex Machina            2.0
Toy Story 4           3.0
Casablanca            4.0
Dune                  4.0
Ghost in the Shell    4.0
Good Will Hunting     5.0
Shutter Island        5.0
Titanic               7.0
Oppenheimer           9.0
Fantastic Mr. Fox     9.0
Name: P15, dtype: float64
Title
Call Me by Your Name     1.0
Edward Scissorhands      2.0
Challengers              3.0
Black Panther            4.0
Nosferatu (1922)         4.0
Ballerina                4.0
Lincoln                  4.0
Moonlight                8.0
Big Hero 6               9.0
Scarface                10.0
Name: P16, dtype: float64
Title
Batman Dark Knight                      1.0
The Perks of Being a Wallflower         1.0
The Batman                              4.0
Children of Men                         4.0
Spider-Man: Across the Spider-Verse     6.0
Kill Bill: Vol. 1                       6.0
F1                                      6.0
Lalaland                                7.0
Spider-Man: Into the Spider-Verse       9.0
Chinatown                              10.0
Prisoners                              10.0
Name: P17, dtype: float64
Title
Star Wars: Episode I - The Phantom Menace      3.0
Anora                                          4.0
Kill Bill: Vol. 1                              4.0
Gone Girl                                      5.0
Mission: Impossible 3                          7.0
Rocky                                          7.0
Baby Driver                                    8.0
Sicario                                        9.0
Scream                                        10.0
Am?lie                                        10.0
Name: P18, dtype: float64
Title
Nop                                    3.0
The Babadook                           3.0
Jojo Rabbit                            4.0
Back to the Future                     5.0
Ghostbusters                           6.0
Adaptation (Ladron de Orquideas)       8.0
Mission: Impossible - Rogue Nation     8.0
Mission: Impossible 3                  9.0
The Truman Show                        9.0
Oppenheimer                            9.0
Lalaland                              10.0
Name: P19, dtype: float64
Title
The Breakfast Club     1.0
Nosferatu (1922)       2.0
Alien: Romulus         3.0
Fantastic Mr. Fox      5.0
Mad Max: Fury Road     5.0
Pulp fiction           8.0
Children of Men        9.0
The Babadook          10.0
Name: P20, dtype: float64

Looking at the ratings and the title of the movies we decided to aknowledge a mistake in the ratings scale so we'll multiply for the correct factor

In [18]:
# multiplies all movie ratings from 0 to 5 times 20 for a correct scale
for col in rating_columns:
    movies[col]=np.where((movies[col]>0)&(movies[col]<=5), movies[col]*20, movies[col])

In [19]:
# multiplies all movie ratings from 0 to 10 times 10 for a correct scale
for col in rating_columns:
    movies[col]=np.where((movies[col]>0)&(movies[col]<=10), movies[col]*10, movies[col])

#### `Genre`

Now, let's explore the `'Genre'` column to see if there are invisible characters.

In [20]:
movies['Genre'].unique()

array(['Romance', 'Terror', 'Comedy', 'Horror', 'Drama', 'Sci-Fi',
       'Action', 'Animation', 'Thriller', 'Western', 'Crime', 'Suspense',
       'War', 'Adventure', 'Mystery', 'Musical', 'Childish',
       'Ciencia ficci«n / Terror', 'Ciencia ficci«n / Acci«n',
       'Biographical', 'Fantasy', 'Sports', 'Historical'], dtype=object)

We can see that SciFi is separated with "-", some double genres separated with "/" and a symbol "«" replacing the ó in spanish genres, so we'll replace them

In [21]:
movies['Genre'] = movies['Genre'].str.replace(' ','') # just in case we didn't notice an space
movies['Genre'] = movies['Genre'].str.replace('-','')
movies['Genre'] = movies['Genre'].str.replace('/','')
movies['Genre'] = movies['Genre'].str.replace('«','on')
movies['Genre'].unique()

array(['Romance', 'Terror', 'Comedy', 'Horror', 'Drama', 'SciFi',
       'Action', 'Animation', 'Thriller', 'Western', 'Crime', 'Suspense',
       'War', 'Adventure', 'Mystery', 'Musical', 'Childish',
       'CienciaficcionnTerror', 'CienciaficcionnAccionn', 'Biographical',
       'Fantasy', 'Sports', 'Historical'], dtype=object)

Now we just need to change the spanish genres, the 'Childish' genre to family and we decided to also change 'Terror' to just 'Horror':

In [22]:
movies['Genre'] = movies['Genre'].replace('Childish', 'Family')
movies['Genre'] = movies['Genre'].replace('CienciaficcionnTerror', 'SciFi')
movies['Genre'] = movies['Genre'].replace('CienciaficcionnAccionn', 'SciFi')
movies['Genre'] = movies['Genre'].replace('Terror', 'Horror')
np.sort(movies['Genre'].astype(str).unique())

array(['Action', 'Adventure', 'Animation', 'Biographical', 'Comedy',
       'Crime', 'Drama', 'Family', 'Fantasy', 'Historical', 'Horror',
       'Musical', 'Mystery', 'Romance', 'SciFi', 'Sports', 'Suspense',
       'Thriller', 'War', 'Western'], dtype=object)

Okey now we have the correct genre names. But we need a final check to see if there is any problem remaining

In [23]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, (500) Days of Summer to The Social Network
Data columns (total 30 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             200 non-null    int64
 1   Runtime          200 non-null    int64
 2   Genre            200 non-null    object
 3   Budget           199 non-null    float64
 4   Revenue          199 non-null    float64
 5   Personal         200 non-null    int64
 6   IMDb             199 non-null    float64
 7   Rotten_Tomatoes  200 non-null    int64
 8   Metacritic       200 non-null    int64
 9   Filmaffinity     200 non-null    int64
 10  P1               181 non-null    float64
 11  P2               174 non-null    float64
 12  P3               179 non-null    float64
 13  P4               181 non-null    float64
 14  P5               187 non-null    float64
 15  P6               188 non-null    float64
 16  P7               179 non-null    float64
 17  P8               176 non-null    float64
 18  P9               176 non-null    float64
 19  P10              181 non-null    float64
 20  P11              186 non-null    float64
 21  P12              184 non-null    float64
 22  P13              174 non-null    float64
 23  P14              181 non-null    float64
 24  P15              177 non-null    float64
 25  P16              180 non-null    float64
 26  P17              185 non-null    float64
 27  P18              179 non-null    float64
 28  P19              179 non-null    float64
 29  P20              186 non-null    float64
dtypes: float64(23), int64(6), object(1)
memory usage: 56.5+ KB

Types and non-null count looks fine. Now, let's verify that the rating columns have the correct scale

In [24]:
movies.iloc[:,3:11].describe()

,Budget,Revenue,Personal,IMDb,Rotten_Tomatoes,Metacritic,Filmaffinity,P1
count,199.000000,199.000000,200.000000,199.000000,200.000000,200.000000,200.000000,181.000000
mean,73.566834,414.496985,78.655000,77.145729,86.545000,77.025000,80.690000,72.016575
std,86.764121,515.116529,6.153479,12.192226,11.492535,11.374589,15.767912,24.244008
min,1.000000,4.100000,52.000000,33.000000,32.000000,43.000000,15.000000,0.000000
25%,14.000000,80.000000,75.000000,69.000000,81.750000,69.000000,74.000000,55.000000
50%,40.000000,235.000000,79.000000,78.000000,90.000000,77.000000,85.000000,80.000000
75%,109.000000,539.650000,83.000000,86.500000,94.000000,86.000000,91.000000,91.000000
max,460.000000,2920.000000,94.000000,100.000000,100.000000,99.000000,100.000000,100.000000

In [25]:
movies.iloc[:,11:21].describe()

,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11
count,174.000000,179.000000,181.000000,187.000000,188.000000,179.000000,176.000000,176.000000,181.000000,186.000000
mean,71.183908,71.351955,72.143646,70.101604,69.670213,73.195531,71.585227,69.585227,68.955801,72.048387
std,25.528644,25.345348,23.423903,25.193132,25.200114,23.559410,26.450679,24.794322,27.457608,25.179632
min,0.000000,0.000000,11.000000,12.000000,12.000000,13.000000,11.000000,12.000000,0.000000,11.000000
25%,54.250000,60.000000,56.000000,52.500000,52.000000,59.500000,58.750000,50.500000,47.000000,58.250000
50%,81.000000,80.000000,80.000000,80.000000,79.000000,80.000000,81.000000,79.500000,81.000000,80.000000
75%,89.750000,91.000000,90.000000,90.000000,90.000000,93.000000,92.000000,89.000000,90.000000,92.000000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [26]:
movies.iloc[:,21:].describe()

,P12,P13,P14,P15,P16,P17,P18,P19,P20
count,184.000000,174.000000,181.000000,177.000000,180.000000,185.000000,179.000000,179.000000,186.000000
mean,70.538043,66.264368,70.055249,73.604520,72.538889,68.740541,71.888268,72.709497,71.413978
std,25.370450,29.432380,27.327179,22.381039,26.024776,26.512256,26.510096,24.709423,24.955650
min,0.000000,11.000000,11.000000,12.000000,12.000000,0.000000,0.000000,11.000000,0.000000
25%,54.750000,40.000000,52.000000,60.000000,58.500000,53.000000,56.500000,59.500000,57.000000
50%,80.000000,79.000000,80.000000,81.000000,82.500000,79.000000,80.000000,81.000000,80.000000
75%,89.000000,92.000000,91.000000,90.000000,91.000000,89.000000,91.500000,91.000000,89.000000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

Everything looks perfect so now we'll sace the clean data set into a csv file named 'Team6_clean'

### Save dataframe to disk

In [27]:
#movies.to_csv('Team6_clean.csv')